const REQUEST_START = 'REQUE_START'
const REQUEST_END = 'REQUEST_END'
const RIGHT_FLIP='RIGHT_FLIP'
const LEFT_FLIP='LEFT_FLIP'
const SORT_LIST='SORT_LIST'
const LIKE_MOVIE='LIKE_MOVIE'
const BLOCK_MOVIE='BLOCK_MOVIE'

export {
    REQUEST_START,
    REQUEST_END,
    RIGHT_FLIP,
    LEFT_FLIP,
    SORT_LIST,
    LIKE_MOVIE,
    BLOCK_MOVIE
}